"""Endpoint wrappers exposed through [`MermaidClient`][datamermaid.client.MermaidClient]."""

from __future__ import annotations

from .aggregated import (
    AGGREGATED_FAMILIES,
    AggregatedFamilyResource,
    AggregatedViewFamily,
    BleachingQCFamilyResource,
)
from .base import BaseResource, ReadOnlyResource, Resource
from .choices import ChoicesResource
from .me import MeResource
from .project_context import (
    PROJECT_RESOURCES,
    ProjectBeltFishMethodsResource,
    ProjectBeltInvertMethodsResource,
    ProjectBenthicLITMethodsResource,
    ProjectBenthicPITMethodsResource,
    ProjectBenthicPQTMethodsResource,
    ProjectBenthicTransectsResource,
    ProjectBleachingQCMethodsResource,
    ProjectContext,
    ProjectFishBeltTransectsResource,
    ProjectHabitatComplexityMethodsResource,
    ProjectManagementsResource,
    ProjectObserversResource,
    ProjectProfilesResource,
    ProjectResource,
    ProjectSampleEventsResource,
    ProjectSitesResource,
)
from .projects import ProjectsResource
from .reference import (
    REFERENCE_RESOURCES,
    BenthicAttributesResource,
    FishFamiliesResource,
    FishGeneraResource,
    FishSizesResource,
    FishSpeciesResource,
    InvertAttributesResource,
    InvertSpeciesResource,
    LabelMappingsResource,
    ManagementsResource,
    ProjectTagsResource,
    SitesResource,
    SummarySampleEventsResource,
)
from .zonal_stats import (
    ZONAL_STATS_ENDPOINTS,
    BatchItem,
    RasterStacStatsEndpoint,
    RasterStatsEndpoint,
    Stat,
    VectorStacStatsEndpoint,
    VectorStatsEndpoint,
    WeightingMethod,
    ZonalStatsEndpoint,
    ZonalStatsResource,
)

__all__ = [
    "AGGREGATED_FAMILIES",
    "PROJECT_RESOURCES",
    "REFERENCE_RESOURCES",
    "ZONAL_STATS_ENDPOINTS",
    "AggregatedFamilyResource",
    "AggregatedViewFamily",
    "BaseResource",
    "BatchItem",
    "BenthicAttributesResource",
    "BleachingQCFamilyResource",
    "ChoicesResource",
    "FishFamiliesResource",
    "FishGeneraResource",
    "FishSizesResource",
    "FishSpeciesResource",
    "InvertAttributesResource",
    "InvertSpeciesResource",
    "LabelMappingsResource",
    "ManagementsResource",
    "MeResource",
    "ProjectBeltFishMethodsResource",
    "ProjectBeltInvertMethodsResource",
    "ProjectBenthicLITMethodsResource",
    "ProjectBenthicPITMethodsResource",
    "ProjectBenthicPQTMethodsResource",
    "ProjectBenthicTransectsResource",
    "ProjectBleachingQCMethodsResource",
    "ProjectContext",
    "ProjectFishBeltTransectsResource",
    "ProjectHabitatComplexityMethodsResource",
    "ProjectManagementsResource",
    "ProjectObserversResource",
    "ProjectProfilesResource",
    "ProjectResource",
    "ProjectSampleEventsResource",
    "ProjectSitesResource",
    "ProjectTagsResource",
    "ProjectsResource",
    "RasterStacStatsEndpoint",
    "RasterStatsEndpoint",
    "ReadOnlyResource",
    "Resource",
    "SitesResource",
    "Stat",
    "SummarySampleEventsResource",
    "VectorStacStatsEndpoint",
    "VectorStatsEndpoint",
    "WeightingMethod",
    "ZonalStatsEndpoint",
    "ZonalStatsResource",
]
